# Site settings
title: Romeow Was Here
tagline: "MEOW!"
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
port: 8080



# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]